Dvc 5114 js sdk remove id from localstorage on reset
DevCycleHQ/js-sdks pull request #324
Opened 2022-11-15 18:22 UTC by L-Joli

2022-11-16 17:55 UTC, rodeora requested changes

2022-11-16 17:55 UTC, rodeora commented on sdk/js/src/Client.ts
> +        this.store.store?.removeItem(StoreKey.AnonUser)
use the store.clear function instead

2022-11-16 17:55 UTC, rodeora commented on sdk/js/src/Client.ts
> -
we also need to save this new anonUser's id to the store here

2022-11-16 17:55 UTC, rodeora commented on sdk/js/__tests__/Client.spec.js
> +            expect(anonymousId).toBeNull()
we should be checking that the new anon user created by reset() exists here

2022-11-18 18:42 UTC, kaushalkapasi approved these changes

2022-11-18 18:48 UTC, rodeora approved these changes

2022-11-18 18:48 UTC, merged